### ISSUE TITLE
Advanced Auctions

### ISSUE THREAD

**Issue by janus-reith** [simonpfry/AuctionHouse#26]
Well, not really an issue:

Im learning to use nodejs with meteor stack and this Auction web app atm, 
and really like it so far.

I have a special use case:
An auction should consist of two rounds: In one round everyone can bid once.
When this round is finished, a second round starts and the 3 highest bidders can bid with each other like usual.

**Does it make sense to use this project to get this started, or would the modifications I need to do
take up more time than starting from scratch?**

**Comment by simonpfry** [comment]
Hey @janus-reith.

I really like your idea, it would be great if this platform could do different variations of auction. The biggest issue I can see adding rounds of bidding is at the moment there is no real system for bidder user accounts, just the user putting their name, which can easily be changed. This would make the system somewhat fragile if, in the second round, all someone needs to do is be the same name as someone who was top three in the previous rounds to interfere.

Ideally you'd want to solve this with a proper sign up system, which is super easy to do in Meteor, but I didn't previously bother with because the system was only being used by people in the room, so it policed itself.

In terms of starting from scratch or not, as this project is a little old now and Meteor has come on and changed a bit since I started, I feel it's probably best to start over, but use anything you find in here which is useful as inspiration. Especially if you're going to add a user sign up flow, and therefore add new pages and new routing into the app, starting fresh might be easier.

**Comment by janus-reith** [comment]
Thanks for your answer, I will probably start from scratch, but this will still be very helpful.
